# Generated by Django 3.2.9 on 2021-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_devicetype_importer', '0002_netbox_devicetype_importer'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadevicetype',
            name='imported_dt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
