# Generated by Django 4.0.3 on 2022-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_devicetype_importer', '0004_netbox_devicetype_importer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadevicetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
