# Generated by Django 4.0.4 on 2022-04-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_devicetype_importer', '0005_netbox_devicetype_importer'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadevicetype',
            name='type',
            field=models.CharField(default='device-types', max_length=20),
        ),
    ]
